"""Mapping of Python import names to PyPI package names.

For most packages, the import name equals the pip install name. This table
covers the common exceptions. Extend it as new mismatches are discovered
during enrichment.

To add new mappings discovered during enrichment:
1. Add the mapping here: 'import_name': 'pip-package-name'
2. Run tests: python -m unittest tests/test_scan_deps.py
3. Commit with message: "scan-deps: add import mapping X -> Y"

You can also use:
    labeille registry set-field import_name VALUE --where package=NAME --apply
to update the registry, which scan-deps will cross-reference.
"""

from __future__ import annotations

# import_name -> pip_package_name
# Keys use underscores (Python import form), not hyphens.
IMPORT_TO_PIP: dict[str, str] = {
    # --- Imaging / Media ---
    "PIL": "Pillow",
    "cv2": "opencv-python",
    "skimage": "scikit-image",
    # --- Scientific / Data ---
    "sklearn": "scikit-learn",
    "yaml": "PyYAML",
    "bs4": "beautifulsoup4",
    "dateutil": "python-dateutil",
    "attr": "attrs",
    "pkg_resources": "setuptools",
    "setuptools": "setuptools",
    "numpy": "numpy",
    "scipy": "scipy",
    "pandas": "pandas",
    "matplotlib": "matplotlib",
    "mpl_toolkits": "matplotlib",
    "serial": "pyserial",
    "usb": "pyusb",
    "wx": "wxPython",
    "gi": "PyGObject",
    "lxml": "lxml",
    # --- Crypto / Security ---
    "OpenSSL": "pyOpenSSL",
    "Crypto": "pycryptodome",
    "Cryptodome": "pycryptodome",
    "nacl": "PyNaCl",
    "jwt": "PyJWT",
    "josepy": "josepy",
    "paramiko": "paramiko",
    "bcrypt": "bcrypt",
    # --- Web / HTTP ---
    "websocket": "websocket-client",
    "socks": "PySocks",
    "httptools": "httptools",
    "h11": "h11",
    "h2": "h2",
    "hpack": "hpack",
    "wsproto": "wsproto",
    "flask": "Flask",
    "werkzeug": "Werkzeug",
    "jinja2": "Jinja2",
    "markupsafe": "MarkupSafe",
    "starlette": "starlette",
    "fastapi": "fastapi",
    "uvicorn": "uvicorn",
    "gunicorn": "gunicorn",
    "httpx": "httpx",
    "httpcore": "httpcore",
    "aiohttp": "aiohttp",
    "tornado": "tornado",
    "django": "Django",
    "rest_framework": "djangorestframework",
    "asgiref": "asgiref",
    "itsdangerous": "itsdangerous",
    "blinker": "blinker",
    # --- Cloud / Infrastructure ---
    "google": "google-cloud-core",
    "google.cloud.storage": "google-cloud-storage",
    "google.cloud.bigquery": "google-cloud-bigquery",
    "google.cloud.pubsub": "google-cloud-pubsub",
    "google.cloud.firestore": "google-cloud-firestore",
    "google.cloud.logging": "google-cloud-logging",
    "boto3": "boto3",
    "botocore": "botocore",
    "azure": "azure-core",
    "docker": "docker",
    "kubernetes": "kubernetes",
    # --- Async ---
    "trio": "trio",
    "anyio": "anyio",
    "aiosignal": "aiosignal",
    "frozenlist": "frozenlist",
    "multidict": "multidict",
    "yarl": "yarl",
    "async_timeout": "async-timeout",
    "uvloop": "uvloop",
    # --- Testing ---
    "_pytest": "pytest",
    "py": "py",
    "pluggy": "pluggy",
    "trustme": "trustme",
    "hypothesis": "hypothesis",
    "mock": "mock",
    "factory": "factory-boy",
    "faker": "Faker",
    "freezegun": "freezegun",
    "responses": "responses",
    "respx": "respx",
    "pytest_asyncio": "pytest-asyncio",
    "pytest_mock": "pytest-mock",
    "pytest_cov": "pytest-cov",
    "pytest_timeout": "pytest-timeout",
    "pytest_xdist": "pytest-xdist",
    "xdist": "pytest-xdist",
    "pytest_httpserver": "pytest-httpserver",
    "pytest_benchmark": "pytest-benchmark",
    "pytest_lazy_fixture": "pytest-lazy-fixture",
    "pytest_lazy_fixtures": "pytest-lazy-fixtures",
    "pytest_randomly": "pytest-randomly",
    "pytest_subtests": "pytest-subtests",
    "flaky": "flaky",
    "time_machine": "time-machine",
    "covdefaults": "covdefaults",
    # --- Serialization ---
    "dotenv": "python-dotenv",
    "magic": "python-magic",
    "rapidfuzz": "rapidfuzz",
    "msgpack": "msgpack",
    "toml": "toml",
    "tomli": "tomli",
    "tomli_w": "tomli-w",
    "ujson": "ujson",
    "orjson": "orjson",
    "simplejson": "simplejson",
    "ruamel": "ruamel.yaml",
    "xmltodict": "xmltodict",
    "defusedxml": "defusedxml",
    # --- CLI / Display ---
    "platformdirs": "platformdirs",
    "appdirs": "appdirs",
    "click": "click",
    "rich": "rich",
    "colorama": "colorama",
    "tqdm": "tqdm",
    "pygments": "Pygments",
    "tabulate": "tabulate",
    "termcolor": "termcolor",
    "shellingham": "shellingham",
    "typer": "typer",
    "cleo": "cleo",
    # --- Parsing ---
    "pyparsing": "pyparsing",
    "ply": "ply",
    "parso": "parso",
    "jedi": "jedi",
    "regex": "regex",
    "chardet": "chardet",
    "charset_normalizer": "charset-normalizer",
    # --- Networking ---
    "dns": "dnspython",
    "idna": "idna",
    "certifi": "certifi",
    "urllib3": "urllib3",
    "requests": "requests",
    "requests_oauthlib": "requests-oauthlib",
    "requests_toolbelt": "requests-toolbelt",
    "oauthlib": "oauthlib",
    "rsa": "rsa",
    # --- Data formats ---
    "jsonschema": "jsonschema",
    "jsonpath_ng": "jsonpath-ng",
    "jsonpointer": "jsonpointer",
    "jsonpatch": "jsonpatch",
    "referencing": "referencing",
    "isodate": "isodate",
    "arrow": "arrow",
    "pendulum": "pendulum",
    "dateparser": "dateparser",
    # --- Protobuf / gRPC ---
    "google.protobuf": "protobuf",
    "google.api_core": "google-api-core",
    "google.auth": "google-auth",
    "grpc": "grpcio",
    "proto": "proto-plus",
    # --- Build tools ---
    "build": "build",
    "installer": "installer",
    "hatchling": "hatchling",
    "flit_core": "flit-core",
    "poetry": "poetry",
    "setuptools_scm": "setuptools-scm",
    # --- Type checking ---
    "mypy": "mypy",
    "mypy_extensions": "mypy-extensions",
    "typing_extensions": "typing-extensions",
    "typing_inspect": "typing-inspect",
    "typing_inspection": "typing-inspection",
    "annotated_types": "annotated-types",
    # --- Misc ---
    "psutil": "psutil",
    "wrapt": "wrapt",
    "decorator": "decorator",
    "six": "six",
    "more_itertools": "more-itertools",
    "sortedcontainers": "sortedcontainers",
    "cachetools": "cachetools",
    "filelock": "filelock",
    "tenacity": "tenacity",
    "backoff": "backoff",
    "deprecated": "Deprecated",
    "dill": "dill",
    "cloudpickle": "cloudpickle",
    "joblib": "joblib",
    "sniffio": "sniffio",
    "exceptiongroup": "exceptiongroup",
    "smmap": "smmap",
    "gitdb": "gitdb",
    "git": "GitPython",
    "dulwich": "dulwich",
    "pexpect": "pexpect",
    "ptyprocess": "ptyprocess",
    "wcwidth": "wcwidth",
    "prompt_toolkit": "prompt-toolkit",
    "IPython": "ipython",
    "ipykernel": "ipykernel",
    "zmq": "pyzmq",
    "traitlets": "traitlets",
    "nbformat": "nbformat",
    "nbconvert": "nbconvert",
    "jupyter_client": "jupyter-client",
    "jupyter_core": "jupyter-core",
    "nest_asyncio": "nest-asyncio",
    "pydantic": "pydantic",
    "pydantic_core": "pydantic-core",
    "pydantic_settings": "pydantic-settings",
    "marshmallow": "marshmallow",
    "dataclasses_json": "dataclasses-json",
    "typedload": "typedload",
    "cattrs": "cattrs",
    "cffi": "cffi",
    "pycparser": "pycparser",
    "asn1crypto": "asn1crypto",
    "pyasn1": "pyasn1",
    "pyasn1_modules": "pyasn1-modules",
    "msal": "msal",
    "msal_extensions": "msal-extensions",
    "sentry_sdk": "sentry-sdk",
    "newrelic": "newrelic",
    "ddtrace": "ddtrace",
    "opentelemetry": "opentelemetry-api",
    "prometheus_client": "prometheus-client",
    "markdownit": "markdown-it-py",
    "mdurl": "mdurl",
    "soupsieve": "soupsieve",
    "webencodings": "webencodings",
    "html5lib": "html5lib",
    "cssselect": "cssselect",
    "tinycss2": "tinycss2",
    "pathspec": "pathspec",
    "editables": "editables",
    "nodeenv": "nodeenv",
    "identify": "identify",
    "cfgv": "cfgv",
    "virtualenv": "virtualenv",
    "distlib": "distlib",
    "distro": "distro",
    "zstandard": "zstandard",
    "lz4": "lz4",
    "brotli": "brotli",
    "PIL.Image": "Pillow",
    "aiofiles": "aiofiles",
    "propcache": "propcache",
    "pretend": "pretend",
    "objgraph": "objgraph",
    "testpath": "testpath",
    "aioresponses": "aioresponses",
}
